### ISSUE TITLE
Can't install the plugin

### ISSUE THREAD

**Issue by vaoan** [jlkeesey/Chatter#6]
![image](https://github.com/jlkeesey/Chatter/assets/3722960/38e113be-8795-4767-8d46-06303c83521f)
 I keep getting an error trying to install this plugin. Is there a way to fix this? Thank you again for this plugin. Has been my favorite way to keep logs saved and organized and would love to continue using it

**Comment by jlkeesey** [comment]
Pull request merged, built, tested, and submitted to Dalamud.
